grails:
    controllers:
        upload:
            maxFileSize: 104857600      
            maxRequestSize: 104857600
restinterface:
    capabilities:
        - import-domino-json
        - java-domino-gradle
        - nsfodp
        - upload-database
        - upload-html
    serverName:  demo/DEMO
    baseURL:  https://127.0.0.1:8080
